### PR TITLE
KEYCLOAK-9881: add postgres connection fail-over url

### PR DESCRIPTION
**Pull request by malmuzaini**
jdbc allow connection fail-over for postgres. Please refer to https://jdbc.postgresql.org/documentation/head/connect.html

### CODE REVIEW

**Comment by stianst** [comment]
Adding yet another DB vendor (postgres-ha) that is configured differently is not the correct approach here. Would be better to allow the DB_HOST to be a list. Makes it a bit tricky with DB_PORT if different hosts have different ports. Having that as a separate variable was probably a mistake from the start.

I'd suggest allowing DB_HOST to contain a comma separated list and also allowing including the port. So valid values could be:

DB_HOST=host1
DB_HOST=host1,host2
DB_HOST=host1:5643,host2:6757

We should make DB_PORT optional and if it is added then it's added to all hosts.

Please also create a corresponding JIRA for this PR.

**Comment by stianst** [comment]
Closing due to lack of feedback

**Comment by malmuzaini** [comment]
I opened this issue KEYCLOAK-9881.
I totally agree with your suggestion let me fix it.

**Comment by malmuzaini** [comment]
@stianst Can you please reopen the PR!

**Comment by malmuzaini** [comment]
> Adding yet another DB vendor (postgres-ha) that is configured differently is not the correct approach here. Would be better to allow the DB_HOST to be a list. Makes it a bit tricky with DB_PORT if different hosts have different ports. Having that as a separate variable was probably a mistake from the start.
> 
> I'd suggest allowing DB_HOST to contain a comma separated list and also allowing including the port. So valid values could be:
> 
> DB_HOST=host1
> DB_HOST=host1,host2
> DB_HOST=host1:5643,host2:6757
> 
> We should make DB_PORT optional and if it is added then it's added to all hosts.
> 
> Please also create a corresponding JIRA for this PR.

The hosts along with their ports should be passed as a single value, like this:
DB_ADDR=host1:5643,host2:6757
So the format should be host:port and if there is more than one host they should be separated by comma.
DB_PORT will be removed for postgres. So even if it's passed it will be ignored in case the driver is postgres.

What your say?

**Comment by stianst** [comment]
We can't just remove DB_PORT as folks may depend on it. We also need to keep this consistent across all DBs.

DB_PORT should be marked as deprecated with the new approach setting the port as part of DB_HOST. If DB_PORT is set it can be appended to DB_HOST in the case DB_HOST contains a single host and does not have the port set. That is probably the simplest option that is still backwards compatible.

**Comment by malmuzaini** [comment]
I am aware of this fact.

You said " If DB_PORT is set it can be appended to DB_HOST in the case DB_HOST contains a single host and does not have the port set. That is probably the simplest option that is still backwards compatible."

This is a logic, and it's not a straight one, so it's hard to implement in the cli file. So I am thinking to implement it in docker-entrypoint.sh, what your say @s01ipsist

**Comment by malmuzaini** [comment]
@stianst Could you please reply

**Comment by stianst** [comment]
Sorry for lack of response, missed this one. Yes, logic can't be handled in CLI so would need to be handled in docker-entrypoint.sh

**Comment by slaskawi** [comment]
@stianst @malmuzaini What is the status of this PR? As far as I can tell from the comments, it is ready to be merged.

**Comment by stianst** [comment]
This is not ready to be merged as it needs to incorporate the changes that was discussed first.

**Comment by malmuzaini** [comment]
Allow me to the end of this weak to apply the changes as discussed.

**Comment by malmuzaini** [comment]
@stianst @slaskawi Please review

**Comment by stianst** [comment]
Approach looks good to me. Haven't had a chance to try it out yet though. Perhaps @slaskawi could do that?

Also, wondering if this shouldn't also be applied to all DBs? As far as I know it's common to have a comma separate list in the JDBC URI. At least MySQL does that:
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-config-failover.html

I know it's out of the scope of what you wanted, but would be a nice addition.

**Comment by malmuzaini** [comment]
@stianst Thank you. I agree since our concern was postgres, I opened the issue for postgres. But as you said it's possible for the other DBs. I am willing to do it for the other DBs, but is it ok to but it in this PR?

**Comment by malmuzaini** [comment]
@stianst &  @slaskawi could you please look into this PR

**Comment by slaskawi** [comment]
@malmuzaini @stianst This looks fine to me. I'm OK with merging it as is.

As @stianst, it would be great to provide this kind of functionality for other DBs as well. Whether it should be done in this PR or in a separate - it's up to you, @malmuzaini.

Thanks for a great work!

**Comment by malmuzaini** [comment]
@slaskawi @stianst I prefer to create a new one one for the others. So let's merge this. 🙌🏽

**Comment by malmuzaini** [comment]
@slaskawi @stianst Plz merge this

**Pull request merged**
