### PR TITLE
update base image to wildfly10.1.0.Final

### PR DESCRIPTION
**Pull request by diuis**
Is it possible to update the base Wildfly image for Keycloak adapter to the version 10.1.0.Final?

### CODE REVIEW

**Comment by diuis** [comment]
@stianst Could you take a look?

**Comment by diuis** [comment]
@stianst @goldmann @abstractj @jpkrohling @ahus1 Hi guys! someone could take a look at this PR?
Thanks!

**Comment by stianst** [comment]
Sorry, didn't mean to close the PR. Will take a look or get someone to look soon

**Comment by abstractj** [comment]
@stianst I can look at this.

**Comment by abstractj** [comment]
@stianst good to merge, I just don't have the rights for it :P

**Pull request merged**
