### PR TITLE
KEYCLOAK-10635: Add Oracle database support

### PR DESCRIPTION
**Pull request by nerdstep**
Not sure if this PR is welcome, since supporting Oracle is a little funky, with needing to manually download the OJDBC driver. You'll see I put a check in `build-keycloak.sh` to test for the existence of the `ojdbc*.jar` file (as specified by `JDBC_ORACLE_VERSION`)

To test this, I used Oracle XE 11g provided by the [sath89/oracle-xe-11g](https://hub.docker.com/r/sath89/oracle-xe-11g/) Docker image, which is the same instructions I provided in the README.

### CODE REVIEW

**Comment by stianst** [comment]
I'm OK with including support for Oracle, but it should not require building the image.

Instructions for using Oracle should provide two options on how to include the JDBC driver. One is to mount driver to required path in the image, second is to extend the image to add the driver.

**Comment by nerdstep** [comment]
Yep I agree. I'm not familiar with how to extend an image but I can look into it and update the PR accordingly.

**Comment by nerdstep** [comment]
@stianst can you please review the changes?

**Comment by slaskawi** [comment]
@nerdstep @stianst What is the status of this PR? I see some pushes from @keycloak-bot and some test runs from `dockercloud`. I'm a bit confused...

**Comment by nerdstep** [comment]
@slaskawi From my perspective the PR is ready unless there are any additional changes requested. Should I open a ticket in Jira to request the PR be merged? Not sure what the expectation here is...

**Comment by slaskawi** [comment]
@nerdstep Just a friendly reminder about the items I asked to be implemented.

**Comment by nerdstep** [comment]
@slaskawi thanks for the nudge--got a little sidetracked there. I squashed the commits and opened a ticket.

**Pull request merged**
