### PR TITLE
add SAML adapter to wildfly image

### PR DESCRIPTION
**Pull request by cainj13**
Per @stianst 's comment on #74 , just adding the SAML adapter to the same wildfly server as the OIDC adapter.

Going to leave the old PR out there - some folks that only use one or the other might not like having the additoinal subsystems installed on the wildfly server...

### CODE REVIEW

**Comment by cainj13** [comment]
bump.  Any thoughts?

**Comment by cainj13** [comment]
@stianst any more thoughts here?

**Comment by stianst** [comment]
@cainj13 been on holiday last 4 weeks. Will take a look soon.

**Comment by cainj13** [comment]
@stianst  bump.

**Comment by stianst** [comment]
Thanks for the bump ;)

**Pull request merged**
