### PR TITLE
Import/export extended as documented

### PR DESCRIPTION
**Pull request by damianprzygodzki**
To be able to do some migrations, init configuration i had to change docker-entrypoint tool. Followed this chapter https://www.keycloak.org/docs/3.3/server_admin/topics/export-import.html

### CODE REVIEW

**Comment by mxdlx** [comment]
You have a typo, both lines 38 and 58 you wrote `singeFile` but it must say `singleFile`. Thank you so much for this PR. I was completely lost at this importing thing.

**Comment by damianprzygodzki** [comment]
@mxdlx Yes! Thanks! Fixed already.

Also changed a bit headers for those section to be more accurate because we can dump everything, not just realms.

I respect the openness and quick response. Keen to see it merged :)

**Comment by damianprzygodzki** [comment]
Sure man.

**Comment by stianst** [comment]
This is missing a JIRA. It's also missing updates to README.md to document the additional values.

Finally, it will break existing users that just use KEYCLOAK_IMPORT as it requires setting KEYCLOAK_MIGRATION_MODE. It should default to singleFile if not specified so existing it doesn't break for existing users.

**Comment by slaskawi** [comment]
Any update on this one, @damianprzygodzki ?

**Comment by stianst** [comment]
Closing this due to lack of feedback from reporter. Feel free to reopen once comments have been resolved.

**Comment by EagleIJoe** [comment]
@stianst  I created a JIRA (https://issues.redhat.com/browse/KEYCLOAK-15539) and would like to fix the missing default setting. What is the best way to add to this PR? Or do I have to create a new one after cherry picking?

**Comment by mokrueger** [comment]
Sounds like a good feature. Any updates yet?

**Pull request closed without merging**
